### ISSUE TITLE
"Cool URIs don't change"

### ISSUE THREAD

**Issue by birkenbihl** [InternetSociety/web-site-feedback#12]
Maybe you consider this a minor issue.
Some Chapters (e.g. the German Chapter) syndicate news from the Internet Society Web site using the RSS feed.
As it happened before: with the relaunch of the Web site the URI for the feed changed. This produces an error on every Website that syndicates news from the Internet Society.
Problems like this where addressed by Tim Berners-Lee in his article ""Cool URIs don't change" https://www.w3.org/Provider/Style/URI.
Suggested fix (I fixed it for "https://www.isoc.de/" by installing the new URI): 
rewrite/redirect "http://www.internetsociety.org/headlines/rss"  "https://www.internetsociety.org/feed/"

**Comment by danyork** [comment]
@birkenbihl - Hmm... I thought we had redirected all the old RSS feeds to the new ones, but in looking at our redirection log I see that we do not have "/headlines/rss" there. That has now been fixed.

And yes, I'm well aware of TBL's article on this (and other various rants, including my own). We've tried to ensure that most URIs work from the old site to the new site, either by maintaining the old URIs or via redirection. We still have some work to do with the blog posts, but we've tried to have most other links redirect.  I'm still watching the 404 logs and installing more redirects as needed.

Thanks for the report on this one. RSS feeds are critical to me.
