### ISSUE TITLE
404 by chance

### ISSUE THREAD

**Issue by birkenbihl** [InternetSociety/web-site-feedback#13]
_by using Zoom (zoom.us) (https://www.internetsociety.org/chapter-webex-support)_ on _https://www.internetsociety.org/chapters/resources/_ produces a 404

**Comment by birkenbihl** [comment]
fixed obviously

**Comment by birkenbihl** [comment]
Was fixed but not permanently. Error is back.

**Comment by birkenbihl** [comment]
Was fixed but not permanently. Issue is back.

**Comment by danyork** [comment]
@birkenbihl - Hmmm... was the issue that the link for "zoom.us" was set to go to https://www.internetsociety.org/chapter-webex-support ?  If so, that is no longer the case. I'm not seeing that link anywhere on the page. Can we close this issue out?  Or are you still seeing the link?

**Comment by birkenbihl** [comment]
Answer to the question: yes.
Seems fixed again.
