### ISSUE TITLE
Trustee's Committees

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#15]
Only the Nominations and Elections committees are listed.

**Comment by danyork** [comment]
Thanks, Sean. I do now have the text of the remaining charters and we'll be getting that up online.

**Comment by danyork** [comment]
Sean, it's clear from a review that the original thought around https://www.internetsociety.org/board-of-trustees/committees/ is not workable.  There are two issues:

1. Adding all the committees to the single page is going to make it enormous.
2. We need some way to have the committee minutes brought in for those committees that publicly publish minutes.

Our current thinking is to rework that section into a series of child pages.  It will look like this:

committees/  - some intro text about the BoT's use of committees
  - charters/   - the "All Committees" text and the list of current committees
      - audit/
      - elections/
      - ....
  - minutes/
      - executive/
      - finance/
      - ....

The result would look like this image: 
![isoc-bot-committee-page-structure](https://user-images.githubusercontent.com/41662/33612263-0b9db8f0-d99f-11e7-82d1-95f2f3d309f1.png)

**Comment by seanturner** [comment]
I can live with that.

spt

**Comment by danyork** [comment]
Thanks, Sean - we have work underway with the goal to complete this by the end of the year.

**Comment by danyork** [comment]
Closing this issue as the work has now been completed at https://www.internetsociety.org/board-of-trustees/committees/
