### ISSUE TITLE
404s on https://www.internetsociety.org/policybriefs/encryption/

### ISSUE THREAD

**Issue by birkenbihl** [InternetSociety/web-site-feedback#17]
The following links produce a 404 on https://www.internetsociety.org/policybriefs/encryption/:
> Internet Society responds to reports of the U.S. Government’s Circumvention of Encryption Technology, https://www.internetsociety.org/news/internet-society-responds-reports-us-government’s-circumvention-encryption-technology
> Internet Society submission to the UN Special Rapporteur on the Protection and Promotion of the Right
to Freedom of Expression and Opinion regarding the use of encryption and anonymity in digital communications, http://www.internetsociety.org/doc/internet-society-submission-un-special-rapporteur-protection-and-promotion-right-freedom
beside this: take a closer look at the source and check if they are build properly (looks rather insane):

<a href="file:///\\localhost\%3E%09http\::www.internetsociety.org:news:internet-society-responds-reports-us-government%25E2%2580%2599s-circumvention-encryption-technology">Internet Society responds to reports of the U.S. Government’s Circumvention of Encryption Technology</a>, <a href="https://www.internetsociety.org/news/internet-society-responds-reports-us-government%E2%80%99s-circumvention-encryption-technology">https://www.internetsociety.org/news/internet-society-responds-reports-us-government’s-circumvention-encryption-technology</a>
<a href="file:///\\localhost\%3E%09http\::www.ohchr.org:Documents:Issues:Opinion:Communications:InternetSociety.pdf">Internet Society submission to the UN Special Rapporteur on the Protection and Promotion of the Right<br />
to Freedom of Expression and Opinion regarding the use of encryption and anonymity in digital communications</a>, <a href="http://www.internetsociety.org/doc/internet-society-submission-un-special-rapporteur-protection-and-promotion-right-freedom">http://www.internetsociety.org/doc/internet-society-submission-un-special-rapporteur-protection-and-promotion-right-freedom</a>

**Comment by danyork** [comment]
@birkenbihl - Thanks for the error report. We'll take a look and get that fixed. Thanks!

**Comment by danyork** [comment]
@birkenbihl - Thanks again for the report. We've fixed the links and/or added appropriate redirects so that everything is working again.

Thanks!
