### ISSUE TITLE
https://www.internetsociety.org/feed/ is no valid XML

### ISSUE THREAD

**Issue by birkenbihl** [InternetSociety/web-site-feedback#18]
[copy of email: Problem with ISOC RSS / 9.03.21, 17:49 +0100]
our RSS Syndication of https://www.internetsociety.org/feed/ on https://www.isoc.de/ looks like this:

    RSS-Fehler: https://www.internetsociety.org/feed/ is invalid XML, likely due to invalid characters. XML error: Reserved XML Name at line 2, column 39

Though the message is positively misleading the XML is invalid for a crazy reason: The XML declaration does not start on the first character of the file. (see https://www.w3.org/TR/REC-xml/#sec-prolog-dtd).

**Comment by danyork** [comment]
Wow! That is very bizarre. I can see that there is a blank line at the start of the file. I've not seen that before on a WordPress installation.  I'll raise it with our developer team. Perhaps one of our plugins has injected something.

**Comment by danyork** [comment]
Just an update - we've identified that there is something strange happening in our WordPress theme and are continuing to investigate.

**Comment by birkenbihl** [comment]
Fixed - obviously. Thx.

**Comment by danyork** [comment]
@birkenbihl - Thanks for closing this issue. I meant to do so last week after our developers found a fix in our theme. Thanks for pointing this out!
