### ISSUE TITLE
Still some minor validation Problem with feed

### ISSUE THREAD

**Issue by birkenbihl** [InternetSociety/web-site-feedback#19]
From
> **W3C Feed Validation Service**

For
> [https://www.internetsociety.org/feed](https://www.internetsociety.org/feed)

_Sorry
This feed does not validate.
line 53, column 2: Undefined item element: image (20 occurrences) [help]
<image>_
Just in case you are interested.

**Comment by Wohlfarth** [comment]
Hi @birkenbihl 
Thank you for pointing out that issue.
That feed is now valid.
There was still an <image> tag under the <item> tag. As per https://validator.w3.org/feed/docs/rss2.html - <image> can only be sub-element of <channel>. 
Images to display in the feed are in the <description> tag
With best regards,
Henri
