### ISSUE TITLE
First impressions on iOS 9 Safari iPad mini

### ISSUE THREAD

**Issue by saper** [InternetSociety/web-site-feedback#2]
- [ ] load time in a difficult urban environment (subway) very challenging up to unacceptable. The page is empty most of the time
- [ ] first information shown is blue background and yellow button without a text, for a while
- [ ] orange button to scroll generates too bouncy scroll on this platform (I think it was landscape view)
- [ ] scrolling up and down generates white flashes of no background
- [ ] I personally do not like the concept of having to scroll to see anything meaningful
- [ ] there seems to be a plenty of space on this platform not to need a "hamburger menu"
- [ ] this site (similarly to the previous one) buries too much of the potentially useful stuff behind small menu (esp. for regulars)
- [x] I liked the captions of the stories
- [ ] Drawn pipe icons feel "consistent" but with itself only, not with the site. I have noticed "new icons" first, don't remember getting any actual meaning or at least a hint

This probably needs to be restructured, but hey, it's a first post!

**Comment by danyork** [comment]
Marcin - thanks for all the feedback! I greatly appreciate it. I apologize for the delay in responding (there's been quite a bit of feedback, which is excellent). I will do so soon in more detail.

**Comment by danyork** [comment]
@saper - While I did pass along your feedback to our developers back in June, the site has now moved on and is VERY different from how it was when you first checked it out.  I'm going to close out this issue - but please DO feel free to open up a new issue with any new feedback you have. Thanks for opening this issue and providing your feedback!

P.S. We're still working on speed issues. Hoping to have some solutions this week.

**Comment by saper** [comment]
Of course, it was left open for too long probably now. Thank you!
