### ISSUE TITLE
Menu and Search on landing page

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#4]
On iOS 11.0.1 on iPad2 mini, neither the menu in the upper left nor the search in the upper left seem to work.  Works fine on iOS11.0.1 on iPhone 6s.

**Comment by danyork** [comment]
@seanturner - I'm unfortunately unable to replicate. On my iPad (not mini), I'm able to get to both. Could you please check again?

**Comment by seanturner** [comment]
@danyork I can but not until the end of the week.

**Comment by seanturner** [comment]
@danyork just double checked these and can confirm they're not working on my iPad2 mini.   Still work fine on iPhone 6s.

**Comment by danyork** [comment]
Thanks for the report. Strange that it doesn't work. We'll figure out what we need to do. Just to confirm, are you still running 11.0.1 on the iPad2 mini? Or have you updated to 11.0.3?

**Comment by seanturner** [comment]
Ah no I’ve upgraded to 11.0.3.

spt

**Comment by danyork** [comment]
@seanturner - Coming back to this issue, I was able to find someone with an iPhone 6s and he reported:

- All looks good on a 6s running 11.0.2 - checked three browsers and all OK once the site loads

Can you please see if you are still having an issue with your 6s?   Thanks.

**Comment by seanturner** [comment]
@danyork seems to be fixed.  Granted I’m on 11.2 now.  But, please close this one out.

spt
