### ISSUE TITLE
Images for facebook, twitter, etc links don't appear on iPhone 6s

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#6]
On iOS 11.0.1 on iPhone 6s, the images for the twitter, instagram, etc at the bottom of the page don't render.

![image1](https://user-images.githubusercontent.com/4488966/30935702-7968b4f6-a39f-11e7-8b33-093c9a1b0831.png)

**Comment by danyork** [comment]
@seanturner - could you please check this again?  I've been unable to replicate this. The icons show up fine on my iPad running iOS 11, and on my iPhone running iOS 10.

**Comment by seanturner** [comment]
@danyork Here's another screenshot from when I hold my phone horizontally.  The links work they just seem to show up as boxes.  Note I reloaded the page a couple of times and had the same result.  I'll try to get somebody nearby with a iPhone6s to check it too.

![img_2522](https://user-images.githubusercontent.com/4488966/31132070-b1f6e85e-a810-11e7-9987-1ec6cfea3db6.PNG)

**Comment by danyork** [comment]
Strange. We'll take a look at that and see if we can replicate it.

**Comment by danyork** [comment]
@seanturner - Is this still an issue?  I tried to find anyone who could replicate this and so far can't.

**Comment by seanturner** [comment]
It’s working on the iPad mini on iOS 11.2 (and now 11.2.1)
On my iPhone the links themselves are working, but for whatever reason the icons aren’t showing up.  At this point, I’m thinking this has to be me and you should probably just close this one out.

spt

**Comment by danyork** [comment]
Sean,
I think I'll leave it open for a bit to see if anyone else can see this issue.  I tried a couple of others who had an iPhone 6s and still haven't been able to replicate it. As you said, maybe this is just something particular to your phone.
Dan

**Comment by seanturner** [comment]
Roger - I think it’s all about the operator 😶
