### ISSUE TITLE
indent sub-menu items

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#7]
On iOS 11.0.1 on iPhone 6s, it might be better to indent the sub-menu items, e.g., Key Issues under "What we're doing".

![image1](https://user-images.githubusercontent.com/4488966/30935852-f8e8ff88-a39f-11e7-84cc-89f8d4c87484.png)

**Comment by danyork** [comment]
Thanks for the suggestion. Passing it along to our developers. I agree that it's hard to see what the submenus are.

**Comment by seanturner** [comment]
@danyork I'm closing this out because I see that it is implemented.
