### ISSUE TITLE
Collapse Menu Items

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#8]
On iOS 11.0.1 on iPhone 6s, there's no way to collapse the menu items.  Once you click on "What we're doing" (or the others) it shows the sub-elements but clicking again on "What we're doing" (or the others) it doesn't collapse the list.

**Comment by danyork** [comment]
Verified the bug. Opening a task in our internal Asana tracking. Will report back status.

**Comment by danyork** [comment]
We have a fix we'll be deploying soon. Thanks for the report.

**Comment by okadots** [comment]
@seanturner this has been resolved. thanks!
