### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by seanturner** [InternetSociety/web-site-feedback#9]
Lots of links on https://www.internetsociety.org/issues/encryption/ are 404s:

0. Link to "Statement by the Internet Society Board of Trustees"
1. Link to "Online Dialogue About Encryption" is a 404.
2. Link to "Report: IGF 2015 Workshop – Law enforcement in a world of pervasive encryption".
3. Link to "Let's Encrypt initiative".

On https://www.internetsociety.org/internet/history-internet/ the following links are also 404s:

0. "PBS's Nerds 2.01"
1. "Origins and Nature of the Internet in Australia"
2. "History and Overview of CSNET (PDF: 156KB)"
3. "Internet History and Growth"

**Comment by danyork** [comment]
Thanks for the report. Working to get those fixed. (or with the external sites I'll need to find them or remove them).

**Comment by danyork** [comment]
On https://www.internetsociety.org/internet/history-internet/ the following links are also 404s:

"PBS's Nerds 2.01"
  - It seems PBS no longer has the right to publish this video. Pointed to Internet archive site.

"Origins and Nature of the Internet in Australia"
  - Found updated link - http://www.rogerclarke.com/II/OzI04.html

"History and Overview of CSNET (PDF: 156KB)"
  - Pointed to another location for the PDF: https://www.researchgate.net/publication/2918985_History_And_Overview_Of_Csnet

"Internet History and Growth"
  - Re-linked to the correct file.

**Comment by seanturner** [comment]
@danyork verified these four now work.  When the other four get working just close this issue out.

**Comment by danyork** [comment]
I just realized that I haven't updated this ticket... 3 of the 4 broken links were fixed. The links were fixed on the actual page - and in addition redirections were added so that any other pointers to the link will go to the new pages.

The one remaining link to fix is the pointer to the "Online Dialogue about Encryption."

**Comment by danyork** [comment]
Fixed the last link to https://www.internetsociety.org/events/online-dialogue-about-encryption/ 

Thanks again for the report, Sean.  Closing this issue.
